name: Publish to NPM and Release on Github
on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  release:
    name: Bump Version, Build, and Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Bump Version
        id: bump-version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "Updated version to ${NEW_VERSION}"

      - name: Commit and Push New Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ env.NEW_VERSION }}"
          git push origin main

      - name: Build package
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.NEW_VERSION }}" # Use the version passed from the build job
          name: "Release ${{ env.NEW_VERSION }}" # Name the release with the version.
          generate_release_notes: true # Generate release notes
          draft: false # The release will not be a draft.
          prerelease: false # The release will not be a pre-release.
          body: |
            New release of **expo-check-installed-apps** is available.
            - Version: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
